CREATE TABLE MOVIE(
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(30) NOT NULL,
    PublishTime DATETIME NULL,
    ReleaseData DATETIME NULL,
    OffDate DATETIME NULL,
    Price DOUBLE NULL
)