version: "3.3"
services:
  webapi:
    image: evensnachi/somewhere-cinema
    build:
      context: .
    ports:
      - "7000:7000"
  database:
    image: mysql:latest
    depends_on:
      - webapi
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: somewherecinema
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
    volumes:
<<<<<<< HEAD
      - dbdata:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: always
=======
      - ./db/data:/var/lib/mysql
    ports: 
      - "3306:3306"
    restart: always
    
  flyway:
    image: flyway/flyway
    command: migrate
    volumes:
      - ./db:/flyway/sql 
      - ./db:/flyway/conf
    depends_on:
      - database
    restart: always
        
  webapi:
    depends_on:
      - database
    image: evensnachi/somewhere-cinema
    build:
      context: .
    ports:
      - "7000:7000"
    restart: always
>>>>>>> BackEnd
volumes:
  data: