version: "3.3"
services:
  database:
    image: mysql:latest
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: somewherecinema
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
    volumes:
      - ./db/data:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - net
    restart: always

  flyway:
    image: flyway/flyway
    command: migrate
    volumes:
      - ./db:/flyway/sql 
      - ./db:/flyway/conf
    depends_on:
      - database
    networks:
      - net
  webapi:
    image: evensnachi/somewhere-cinema
    depends_on:
      - database
    build:
      context: .
    ports:
      - "7001:7001"
    networks:
      - net
volumes:
  data:
networks:
  net:
    driver: bridge